{
  "employee": {
    "email": "mock1003.employee203fc802-34c7-4dbb-a26b-a917524c0a59@mock.com",
    "firstName": "Mock 1003",
    "lastName": "Employee 1003"
  },
  "batches": [
    {
      "id": 45,
      "batchId": "TR-1087",
      "name": "Mock Batch 45",
      "startDate": "2020-03-02",
      "endDate": "2020-05-08",
      "skill": "Java/Microservices",
      "location": "Tampa",
      "type": "ROCP",
      "qcNotes": [
        {
          "NoteId": 379,
          "content": "This is a Qc batch note on week 1",
          "week": 1,
          "batchId": "TR-1087",
          "associateId": null,
          "employeeId": "QC-User",
          "type": "QC_BATCH",
          "technicalStatus": "Good",
          "createdOn": null,
          "lastUpdated": null,
          "categories": "JS"
        },
        {
          "NoteId": 402,
          "content": "This is a Qc batch note on week 2",
          "week": 2,
          "batchId": "TR-1087",
          "associateId": null,
          "employeeId": "QC-User",
          "type": "QC_BATCH",
          "technicalStatus": "Poor",
          "createdOn": null,
          "lastUpdated": null,
          "categories": "Kubernetes"
        },
        {
          "NoteId": 425,
          "content": "This is a Qc batch note on week 3",
          "week": 3,
          "batchId": "TR-1087",
          "associateId": null,
          "employeeId": "QC-User",
          "type": "QC_BATCH",
          "technicalStatus": "Average",
          "createdOn": null,
          "lastUpdated": null,
          "categories": "HTML"
        },
        {
          "NoteId": 448,
          "content": "This is a Qc batch note on week 4",
          "week": 4,
          "batchId": "TR-1087",
          "associateId": null,
          "employeeId": "QC-User",
          "type": "QC_BATCH",
          "technicalStatus": "Good",
          "createdOn": null,
          "lastUpdated": null,
          "categories": "TypeScript"
        },
        {
          "NoteId": 471,
          "content": "This is a Qc batch note on week 5",
          "week": 5,
          "batchId": "TR-1087",
          "associateId": null,
          "employeeId": "QC-User",
          "type": "QC_BATCH",
          "technicalStatus": "Poor",
          "createdOn": null,
          "lastUpdated": null,
          "categories": "HTML"
        },
        {
          "NoteId": 494,
          "content": "This is a Qc batch note on week 6",
          "week": 6,
          "batchId": "TR-1087",
          "associateId": null,
          "employeeId": "QC-User",
          "type": "QC_BATCH",
          "technicalStatus": "Average",
          "createdOn": null,
          "lastUpdated": null,
          "categories": "JavaScript"
        },
        {
          "NoteId": 517,
          "content": "This is a Qc batch note on week 7",
          "week": 7,
          "batchId": "TR-1087",
          "associateId": null,
          "employeeId": "QC-User",
          "type": "QC_BATCH",
          "technicalStatus": "Average",
          "createdOn": null,
          "lastUpdated": null,
          "categories": "HTML"
        },
        {
          "NoteId": 540,
          "content": "This is a Qc batch note on week 8",
          "week": 8,
          "batchId": "TR-1087",
          "associateId": null,
          "employeeId": "QC-User",
          "type": "QC_BATCH",
          "technicalStatus": "Good",
          "createdOn": null,
          "lastUpdated": null,
          "categories": "Java"
        },
        {
          "NoteId": 563,
          "content": "This is a Qc batch note on week 9",
          "week": 9,
          "batchId": "TR-1087",
          "associateId": null,
          "employeeId": "QC-User",
          "type": "QC_BATCH",
          "technicalStatus": "Average",
          "createdOn": null,
          "lastUpdated": null,
          "categories": "TypeScript"
        }
      ],
      "assessments": [
        {
          "assessmentId": 44,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 1-0",
          "assessmentType": "Project",
          "weekNumber": 1,
          "batchId": "TR-1087",
          "assessmentCategory": 14,
          "assignmentDate": null,
          "skillCategory": "JDBC",
          "average": 52.96725500713695
        },
        {
          "assessmentId": 45,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 1-1",
          "assessmentType": "Project",
          "weekNumber": 1,
          "batchId": "TR-1087",
          "assessmentCategory": 20,
          "assignmentDate": null,
          "skillCategory": "Hive",
          "average": 50.18904651295055
        },
        {
          "assessmentId": 46,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 2-0",
          "assessmentType": "Presentation",
          "weekNumber": 2,
          "batchId": "TR-1087",
          "assessmentCategory": 31,
          "assignmentDate": null,
          "skillCategory": "Servlet",
          "average": 48.45407108454542
        },
        {
          "assessmentId": 47,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 2-1",
          "assessmentType": "Other",
          "weekNumber": 2,
          "batchId": "TR-1087",
          "assessmentCategory": 9,
          "assignmentDate": null,
          "skillCategory": "Docker",
          "average": 50.878804529255085
        },
        {
          "assessmentId": 48,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 2-2",
          "assessmentType": "Project",
          "weekNumber": 2,
          "batchId": "TR-1087",
          "assessmentCategory": 22,
          "assignmentDate": null,
          "skillCategory": "Spring",
          "average": 50.15002021464434
        },
        {
          "assessmentId": 49,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 3-0",
          "assessmentType": "Project",
          "weekNumber": 3,
          "batchId": "TR-1087",
          "assessmentCategory": 37,
          "assignmentDate": null,
          "skillCategory": "Helm",
          "average": 53.971708582206205
        },
        {
          "assessmentId": 50,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 3-1",
          "assessmentType": "Other",
          "weekNumber": 3,
          "batchId": "TR-1087",
          "assessmentCategory": 3,
          "assignmentDate": null,
          "skillCategory": "TypeScript",
          "average": 52.67644393985922
        },
        {
          "assessmentId": 51,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 3-2",
          "assessmentType": "Verbal",
          "weekNumber": 3,
          "batchId": "TR-1087",
          "assessmentCategory": 38,
          "assignmentDate": null,
          "skillCategory": "Git",
          "average": 43.81650598618117
        },
        {
          "assessmentId": 52,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 4-0",
          "assessmentType": "Verbal",
          "weekNumber": 4,
          "batchId": "TR-1087",
          "assessmentCategory": 27,
          "assignmentDate": null,
          "skillCategory": "Pega",
          "average": 51.10594346306541
        },
        {
          "assessmentId": 53,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 4-1",
          "assessmentType": "Exam",
          "weekNumber": 4,
          "batchId": "TR-1087",
          "assessmentCategory": 18,
          "assignmentDate": null,
          "skillCategory": "Golang",
          "average": 43.46711254119873
        },
        {
          "assessmentId": 54,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 4-2",
          "assessmentType": "Exam",
          "weekNumber": 4,
          "batchId": "TR-1087",
          "assessmentCategory": 12,
          "assignmentDate": null,
          "skillCategory": "GCP",
          "average": 43.61586462367665
        },
        {
          "assessmentId": 55,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 5-0",
          "assessmentType": "Presentation",
          "weekNumber": 5,
          "batchId": "TR-1087",
          "assessmentCategory": 21,
          "assignmentDate": null,
          "skillCategory": "Spark",
          "average": 44.46188922361894
        },
        {
          "assessmentId": 56,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 5-1",
          "assessmentType": "Exam",
          "weekNumber": 5,
          "batchId": "TR-1087",
          "assessmentCategory": 33,
          "assignmentDate": null,
          "skillCategory": "Python",
          "average": 54.59891791777177
        },
        {
          "assessmentId": 57,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 6-0",
          "assessmentType": "Other",
          "weekNumber": 6,
          "batchId": "TR-1087",
          "assessmentCategory": 4,
          "assignmentDate": null,
          "skillCategory": "HTML",
          "average": 57.774235552007504
        },
        {
          "assessmentId": 58,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 6-1",
          "assessmentType": "Verbal",
          "weekNumber": 6,
          "batchId": "TR-1087",
          "assessmentCategory": 27,
          "assignmentDate": null,
          "skillCategory": "Pega",
          "average": 49.604287364266135
        },
        {
          "assessmentId": 59,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 6-2",
          "assessmentType": "Project",
          "weekNumber": 6,
          "batchId": "TR-1087",
          "assessmentCategory": 30,
          "assignmentDate": null,
          "skillCategory": "Unix",
          "average": 49.57842531664805
        },
        {
          "assessmentId": 60,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 6-3",
          "assessmentType": "Verbal",
          "weekNumber": 6,
          "batchId": "TR-1087",
          "assessmentCategory": 23,
          "assignmentDate": null,
          "skillCategory": "Spring Boot",
          "average": 43.96035894480619
        },
        {
          "assessmentId": 61,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 7-0",
          "assessmentType": "Presentation",
          "weekNumber": 7,
          "batchId": "TR-1087",
          "assessmentCategory": 1,
          "assignmentDate": null,
          "skillCategory": "Java",
          "average": 56.69198103655469
        },
        {
          "assessmentId": 62,
          "rawScore": 100,
          "assessmentTitle": "Mock Assessment 7-1",
          "assessmentType": "Exam",
          "weekNumber": 7,
          "batchId": "TR-1087",
          "assessmentCategory": 6,
          "assignmentDate": null,
          "skillCategory": "JS",
          "average": 48.734773023562
        }
      ]
    }
  ]
}